apiVersion: apps/v1
kind: Deployment
metadata:
  name: ekglue
  namespace: discovery
  labels:
    app.kubernetes.io/name: ekglue
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ekglue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ekglue
    spec:
      serviceAccountName: ekglue
      containers:
        - name: ekglue
          image: gcr.io/high-codex-314318/ekglue:0.2.0
          env:
            - name: DEBUG_ADDRESS
              value: ":8081"
            - name: EKGLUE_CONFIG_FILE
              value: /etc/ekglue/config.yaml
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: VERSION_PREFIX
              value: "$(MY_POD_NAME)-"
          readinessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr
                - localhost:9000
            initialDelaySeconds: 1
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /bin/grpc_health_probe
                - -addr
                - localhost:9000
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - name: grpc
              containerPort: 9000
            - name: debug
              containerPort: 8081
          resources:
            requests:
              cpu: 10m
              memory: 128Mi
            limits:
              memory: 128Mi
          volumeMounts:
            - name: config
              mountPath: /etc/ekglue
      volumes:
        - name: config
          configMap:
            name: ekglue-config
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
