apiVersion: v1
kind: Service
metadata:
  name: ekglue
  namespace: discovery
  labels:
    app.kubernetes.io/name: ekglue
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: 9000
      targetPort: 9000
  selector:
    app.kubernetes.io/name: ekglue
