namespace: discovery
commonLabels:
    app: ekglue
resources:
    - namespace.yaml
    - deployment.yaml
    - service.yaml
    - clusterrole.yaml
    - clusterrolebinding.yaml
    - podmonitor.yaml
images:
    - name: ekglue
      newName: registry.jrock.us/ekglue
      newTag: 0.0.2
