resources:
    - name: source
      type: git
      icon: github-circle
      source:
          uri: https://github.com/jrockway/ekglue
    - name: golang-latest
      type: registry-image
      icon: docker
      source:
          repository: golang
          tag: latest
    - name: envoy-latest
      type: registry-image
      icon: docker
      source:
          repository: envoyproxy/envoy
          tag: latest

jobs:
    - name: tests
      public: true
      plan:
          - get: golang-latest
            trigger: true
          - get: envoy-latest
            trigger: true
          - get: source
            trigger: true
          - task: test
            image: golang-latest
            config:
                platform: linux
                inputs:
                    - name: source
                      path: ekglue
                    - name: envoy-latest
                      path: envoy
                params:
                    ENVOY_PATH: "envoy/rootfs/usr/local/bin/envoy"
                run:
                    path: /bin/sh
                    args:
                        - -c
                        - |
                            export ENVOY_PATH=$PWD/$ENVOY_PATH
                            cd ekglue
                            go test -v -race ./...
