resources:
    - name: source
      type: git
      icon: github-circle
      source:
          uri: https://github.com/jrockway/ekglue
    - name: golang-latest
      type: registry-image
      icon: docker
      source:
          repository: golang
          tag: latest

jobs:
    - name: tests
      public: true
      plan:
          - get: golang-latest
            trigger: true
          - get: source
            trigger: true
          - task: test
            image: golang-latest
            config:
                platform: linux
                inputs:
                    - name: source
                      path: ekglue
                run:
                    path: /bin/sh
                    args:
                        - -c
                        - |
                            cd ekglue
                            go test -v -race ./...
